### ISSUE TITLE
Some recommended modules

### ISSUE THREAD

**Issue by o-ibrahim-catch** [catchdigital/catch_all#5]
- Devel

- Webform

- Honeypot

**Comment by Liam-Power** [comment]
Honeypot isn't an effective form of spam protection. Something like invisible recaptcha is a much better method of preventing spam, but requires recaptcha credentials. The spam protection is only useful for websites that have forms on them - See next point.

I've not included webform as not all websites will require the use of webform, this profile is intended to be used as a base for all websites. Webform doesn't take much set up anyway so shouldn't be too much of an issue.

I don't personally use devel as I use xdebug to find out what variables are set, and as it's a developer-only module which doesn't really require any setup.  For this reason, I did not include it as part of the profile. I believe this is something that should be included as part of the drucker composer file.

Happy to discuss this with the rest of the team to get other opinions at our next team meeting.
